project:
  type: book
  output-dir: docs
  
book:
  title: "Sensing Urban Dynamics with WiFi: A Practical Guide"
  author: Juhyeon Park
  search: true
  sidebar:
    collapse-level: 3
    pinned: true
  site-url: https://juhyeonpark.com/wifi-sensing-for-urban-studies/
  repo-url: https://github.com/urbanjuhyeon/wifi-sensing-for-urban-studies/
  date: "2024. 3. 10."
  chapters:
    - index.qmd
    - content/a10-intro.qmd
    - part: content/a20-installation.qmd
      chapters:
      - content/a21-prerequisites.qmd
      - content/a22-initial.qmd
      - content/a23-pisetup.qmd
      - content/a24-deployment.qmd
      - content/a25-testing.qmd
    - part: content/a30-processing.qmd
      chapters:
      - content/a31-preparation.qmd
      - content/a32-aggregation.qmd
      - content/a33-cleaning.qmd      
    - part: content/a40-metric.qmd
      chapters:
      - content/a41-overview.qmd
      - content/a42-location.qmd
      - content/a43-count.qmd
      - content/a44-track.qmd
      - content/a45-identity.qmd
      - content/a46-activities.qmd
    - part: content/a50-casestudy.qmd
      chapters:
      - content/a51-case1.qmd   
      - content/a52-case2.qmd
      - content/a53-case3.qmd
    - part: content/a60-future.qmd
      chapters:
      - content/a61-limitation.qmd
      - content/a62-direction.qmd
    - part: content/a70-further.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]

editor: source
