project:
  type: book
  output-dir: docs

book:
  title: "Sensing Urban Dynamics with WiFi: A Practical Guide"
  author: Juhyeon Park
  search: true
  sidebar:
    collapse-level: 3
    pinned: true
  site-url: https://juhyeonpark.com/wifi-sensing-for-urban-studies/
  repo-url: https://github.com/urbanjuhyeon/wifi-sensing-for-urban-studies/
  date: "2024. 3. 10."
  chapters:
    - index.qmd
    - content/a10-intro.qmd
    - part: content/a20-installation.qmd
      chapters:
      - content/a21-prerequisites.qmd
      - content/a22-initial.qmd
      - content/a23-pisetup.qmd
      - content/a24-software.qmd
      - content/a25-imp.qmd
    - part: content/a30-metric.qmd
      chapters:
      - content/a31-overview.qmd
      - content/a32-location.qmd
      - content/a33-count.qmd
      - content/a34-track.qmd
      - content/a35-identity.qmd
      - content/a36-activities.qmd
    - part: content/a40-casestudy.qmd
      chapters:
      - content/a41-case1.qmd   
      - content/a42-case2.qmd
      - content/a43-case3.qmd
    - part: content/a50-future.qmd
      chapters:
      - content/a51-limitation.qmd
      - content/a52-direction.qmd
    - part: content/a60-further.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
  pdf:
    documentclass: scrbook
    # Fixes 'Undefined control sequence \cellcolor' error
    include-in-header:
      - text: |
          \usepackage[table]{xcolor}

editor: source
