# Preface {.unnumbered}

This book is a dedicated resource for anyone interested in leveraging affordable, commercially available sensors to measure non-motorized traffic in urban environments.

Quantifying non-motorized traffic---such as pedestrians and cyclists---plays a crucial role in urban studies. Understanding the flow and patterns of non-motorized traffic can inform urban planning strategies, enhance public safety, and contribute to the development of sustainable cities. Moreover, sensing technologies provide a robust and non-invasive method for capturing this vital information in real time, offering insights that traditional surveys or manual counts might miss.

The advent of the Internet-of-Things (IoT) has spurred a wave of urban sensing projects worldwide. Examples include the [Array of Things (AoT) in Chicago, USA](https://arrayofthings.github.io/) and [S-DoT in Seoul, Korea](https://github.com/seoul-iotdata/S-DoT_SampleData), which utilize a network of sensors to gather a wide range of data.

With the increasing accessibility of DIY technologies, individuals now have the opportunity to engage with their urban environment in new and innovative ways. These tools democratize the field of urban sensing, previously the domain of expert scientists, by equipping anyone with the interest to build their own sensors.

This book is designed for those interested in understanding and monitoring non-motorized traffic. We provide comprehensive guidance on building your own urban DIY sensors for this purpose. With hands-on advice, practical examples, and detailed breakthroughs, our aim is to empower you with the skills and knowledge necessary to contribute to the rapidly evolving field of urban sensing.

### Scope of this document {.unnumbered}

This document demonstrates 1) how to build a smart sensor that detects pedestrians outdoors through WiFi sensing, and 2) how to analyze the resulting data to produce meaningful insights. This includes:

-   Getting
-   WiFi data preprocessing
-   WiFi data analysis

### Why WiFi sensing? {.unnumbered}

WiFi sensing technologies are among these tools, providing a non-invasive method for monitoring pedestrians outdoors via sensors that detect WiFi packets sent regularly by access points (APs) and WiFi-enabled devices. Most pedestrians today carry smart devices equipped with WiFi network interfaces, and each WiFi packet includes unique 48-bit addresses, known as Media Access Control (MAC) addresses, enabling a device to be tracked by multiple WiFi sensors. Many recent studies have utilized these sensing technologies to identify pedestrian movements and behaviors[^index-1][^index-2][^index-3].

[^index-1]: Duives, D. C., van Oijen, T., & Hoogendoorn, S. P. (2020). Enhancing Crowd Monitoring System Functionality through Data Fusion: Estimating Flow Rate from Wi-Fi Traces and Automated Counting System Data. Sensors (Basel), 20(21). https://doi.org/10.3390/s20216032

[^index-2]: Soundararaj, B., Cheshire, J., & Longley, P. (2019). Estimating real-time high-street footfall from Wi-Fi probe requests. International Journal of Geographical Information Science, 34(2), 325-343,. https://doi.org/10.1080/13658816.2019.1587616

[^index-3]: Zhou, Y., Lau, B. P. L., Koh, Z., Yuen, C., & Ng, B. K. K. (2020). Understanding Crowd Behaviors in a Social Event by Passive WiFi Sensing and Data Mining. IEEE internet of things journal, 1-1,. https://doi.org/10.1109/jiot.2020.2972062
